[package]
org = "sahan"
name = "Pharma"
version = "0.1.0"
distribution = "2201.6.0"

[build-options]
observabilityIncluded = true

[persist]
datastore = "inmemory"
module = "Pharma"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.0.0"

